export const FETCH_MOVIES = 'FETCH_MOVIES';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS';
export const REQUEST_MOVIE_DETAILS_SUCCESS = 'REQUEST_MOVIE_DETAILS_SUCCESS';
export const REQUEST_MOVIE_DETAILS_FAIL = 'REQUEST_MOVIE_DETAILS_FAIL';
